# Generated by Django 4.2.3 on 2023-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.CharField(max_length=255)),
                ('isrc_id', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('territory', models.CharField(max_length=2)),
                ('date', models.DateTimeField()),
                ('sale_type', models.CharField(max_length=1)),
                ('release_title', models.CharField(max_length=255)),
                ('track_title', models.CharField(max_length=255)),
                ('label_id', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('service_id', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('accounting_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=20, max_digits=29)),
                ('total_foreign', models.DecimalField(decimal_places=20, max_digits=29)),
                ('total_local', models.DecimalField(decimal_places=20, max_digits=29)),
                ('total_gross', models.DecimalField(decimal_places=20, max_digits=29)),
                ('total_net', models.DecimalField(decimal_places=20, max_digits=29)),
            ],
        ),
        migrations.CreateModel(
            name='SalesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('UPLOADING', 'Uploading'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='INITIALIZED', max_length=32)),
                ('status_cause', models.CharField(blank=True, max_length=512, null=True)),
                ('filetype', models.CharField(max_length=12)),
                ('filename', models.CharField(max_length=512)),
                ('filesize', models.IntegerField()),
                ('s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('mongo_id', models.CharField(blank=True, max_length=512, null=True)),
                ('execution_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
